Repository CougarCS/CougarCS-Backend, pull requests merged in 2021-06, with the labels that each got.

#56 Event logic clean up
  .github/workflows/node.js.yml
  package.json
  src/api/routes/event.js
  src/config/app.js
  src/utils/config.js
  src/utils/httpLogger.js
  src/utils/logger.js
Labels: updates

#57 Added Cross env for dev
  package.json
  yarn.lock
Labels: enhancement

#58 Notion Integration for Tutoring Page
  .env.local
  package.json
  src/api/routes/tutors.js
  src/config/app.js
  src/utils/api/calls.js
  src/utils/config.js
  test/resources/mockTutors.json
  test/tutors.test.js
  yarn.lock
Labels: enhancement

#60 Events response data change
  src/api/routes/event.js
  test/event.test.js
Labels: enhancement

#61 Added Coverall
  .github/workflows/node.js.yml
  README.md
  src/api/routes/event.js
  src/api/routes/tutors.js
  src/utils/cacheData.js
Labels: documentation
