Repository CougarCS/CougarCS-Backend, pull requests merged in 2021-09, with the labels that each got.

#79 YouTube Endpoint to Serve Videos
  src/api/routes/youtube.js
  src/config/app.js
  src/utils/api/calls.js
  src/utils/config.js
  test/resources/mockVideos.json
  test/youtube.test.js
Labels: enhancement

#105 README update
  README.md
Labels: updates

#117 Payment function updates
  .gitignore
  src/api/routes/payment.js
  src/utils/api/calls.js
  test/payment.test.js
Labels: bug
